version: '3.3'

services:
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_DB=my_store
      - POSTGRES_USER=richard
      - POSTGRES_PASSWORD=admin123
    ports:
      - 5432:5432
    volumes:
      - /postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=root@root.com
      - PGADMIN_DEFAULT_PASSWORD=root
    ports:
      - 5050:80
